---
http_interactions:
- request:
    method: post
    uri: http://api.iugu.dev/v1/accounts/configuration
    body:
      encoding: UTF-8
      string: '{"commission_percent":10}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - Iugu RubyLibrary
      Authorization:
      - Basic ZGV2ZWxvcG1lbnRfYXBpX3Rva2VuOg==
      Accept-Charset:
      - utf-8
      Accept-Language:
      - pt-br;q=0.9,pt-BR
      Content-Type:
      - application/json; charset=utf-8
      Content-Length:
      - '25'
      Host:
      - api.iugu.com
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Mon, 19 Mar 2018 17:27:42 GMT
      Etag:
      - '"ac137e4bfb11f3269ca79d5dd9503184"'
      Vary:
      - Origin
      X-Handledby:
      - api/v1/account#set_configuration
      X-Rack-Cache:
      - invalidate, pass
      X-Request-Id:
      - 824f83f80cc52da9c90c1c09306a4e43
      X-Runtime:
      - '0.551962'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Connection:
      - keep-alive
      Set-Cookie:
      - incap_ses_789_1185448=qOK5CoHPwnBQ9upenBfzCg7zr1oAAAAASmg2r9HxCQfy1eg4L8ib7A==;
        path=/; Domain=.iugu.com
      - nlbi_1185448=L3vRdBjWQnQYMZC0xHKSPgAAAAAaBW/Ou2bS54RHubWsf+sx; path=/; Domain=.iugu.com
      - visid_incap_1185448=InlH0MydS6eKq7fk73AHTw3zr1oAAAAAQUIPAAAAAABXB1IlPcsxkQNcvb/kb7Ob;
        expires=Tue, 19 Mar 2019 13:45:08 GMT; path=/; Domain=.iugu.com
      X-Iinfo:
      - 9-42147108-42147131 NNNN CT(6 5 0) RT(1521480461415 193) q(0 0 0 4) r(7 7)
        U5
      X-Cdn:
      - Incapsula
      Content-Encoding:
      - gzip
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"configuration":{"commission_percent":10}}'
    http_version:
  recorded_at: Mon, 19 Mar 2018 17:27:43 GMT
recorded_with: VCR 4.0.0
